### ISSUE TITLE
Add 'How to Redeem' text input field to offer creation form

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#10]
Add a new field that allows me to add 'How to Redeem' instructions when creating each Gift Pack offer.  This is just a text field.

**Comment by tallmadge** [comment]
Please change this field to read "How to Redeem" (rather than Redemption Notes), and then I'll close this issue.  I know it's a small thing, but if someone else takes this over from me at some point, I want them to understand the field better.  It's specifically to explain to the end user how to redeem the offer.

**Comment by bryce13950** [comment]
done
