### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#12]
- [ ] Swap the sections so that Gift Pack related questions are the top priority.  

- [ ] Swap the answers to “Can I earn new points when I redeem rewards?” and “Can I add a Gift Pack directly to my member account?”

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45602150-83ce1700-b9de-11e8-8c6d-1ad10ebdac03.png)
