### ISSUE TITLE
General comments on the forms

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#13]
- [ ] All fields should start with a capital letter by default except email fields

- [ ] Always provide a way for the user to hide the keyboard or scroll the page if they want to see what comes below the current view.

- [ ] The screen is not scrolling to the 'password' field after entering an email when creating a new member account

- [ ] The screen does not properly scroll down to the next fields on page 2 of the account creation process, making it difficult/impossible to complete the page.

- [ ] Can't get down to the 'Submit' button to send my help message (can't scroll, can't hide keyboard)

![img_3071](https://user-images.githubusercontent.com/13523241/45598834-911bdf00-b9a7-11e8-9134-ef8312b58320.PNG)

**Comment by Stacyadam** [comment]
Forgot to update these after I refactored all of the text inputs. All of the inputs should have the right return key, scroll to the input and have auto capitalization when applicable.
