### ISSUE TITLE
Updating Password

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#14]
We should require the user to first enter their current password, before updating to a new password.  If we're not setup to handle that on the back end at the moment, then just change the label from "Account Password" to "New Password", and we'll keep this as an issue for the next update.

![img_3069](https://user-images.githubusercontent.com/13523241/45598728-3c2b9900-b9a6-11e8-8f63-b0bcae34eb93.PNG)

**Comment by Stacyadam** [comment]
Yeah this is how the website is handling it. I don't think we have it setup to take a current password first. I could put something together on the front end but it would be a little hacky. 

![image](https://user-images.githubusercontent.com/33630849/45602896-b03c6000-b9eb-11e8-9665-846c4ce52269.png)
