### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#15]
I can't seem to tap over to the Loyalty graphic.  When I tap the right arrow I'm just taken to the Gift Packs screen.  

![img_3070](https://user-images.githubusercontent.com/13523241/45598771-bfe58580-b9a6-11e8-87fe-bdb03d30122b.PNG)

**Comment by Stacyadam** [comment]
Added a generous amount of clickable padding to both of these.

![2018-09-16_20-11-37](https://user-images.githubusercontent.com/33630849/45602977-be3eb080-b9ec-11e8-87ba-2a5b872b362f.png)

![2018-09-16_20-11-42](https://user-images.githubusercontent.com/33630849/45602979-c0a10a80-b9ec-11e8-9605-fbfe8af590d6.png)
