### ISSUE TITLE
Extend token expiration

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#16]
The tokens currently appear to be set to expire in 60 minutes.  **I want this extended to 6 months**.  I don't want people being signed out of this app unless they're actively choosing to sign out.

**Comment by bryce13950** [comment]
Tokens can already be used for up to a year. The user should not be logged out after 60 minutes. The tokens only need to be refreshed after 60 minutes. If the user is being logged out at any point then the refresh process should be looked at again.

**Comment by Stacyadam** [comment]
This has been fixed and is sending a request to refresh the token after it has expired and provides the user with a new fresh token. It is no longer requiring the user to sign in again.

**Comment by tallmadge** [comment]
But now the app is getting stuck on the splash page (see below).  This is after closing the app in background, then reopening.

![image-1 10](https://user-images.githubusercontent.com/13523241/45832319-321bda00-bcc7-11e8-911e-d4950c42eebf.jpg)

**Comment by Stacyadam** [comment]
Just realized I had the secondary refresh requests going to `dev-api` instead of the production qa api. So it was trying to refresh a token from a completely different api and failing. Fixed. Pushing another one to TestFlight now.

**Comment by tallmadge** [comment]
This appears to be working.  I'll go ahead and close this for now, and if I notice the issue happen again, I'll reopen or just create a new ticket.
