### ISSUE TITLE
Increase map size on offer profile page

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#17]
Let's increase the height of the map on the offer profile pages by 50%.  Now that I have a more common size phone, I see that there's plenty more space to fill out the page, and the map is a bit tight as is.

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45725658-61c0ca00-bb81-11e8-914d-30f61ce08d30.png)

**Comment by tallmadge** [comment]
looks good!
