### ISSUE TITLE
Removing Member Cards

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#18]
This doesn't do anything yet.  Are we waiting for something on the back end?  If so, @bryce13950 when do you expect we'll have this available?  If it's something you want to push back to the first update (end of October), we can just hide the 'Remove' buttons for now.  Gotta let us know.

![image-1 4](https://user-images.githubusercontent.com/13523241/45658909-586b2b00-bab7-11e8-9ebe-c5b2f40e01c4.jpg)

**Comment by bryce13950** [comment]
The endpoint is `/users/{user_id}/member-cards/{member_card_id}`

**Comment by Stacyadam** [comment]
@bryce13950 Is that endpoint live on the qa api? I was able to delete a member card in the dev environment but the successful deletion needs to be tweaked on the ui side.

**Comment by bryce13950** [comment]
That endpoint is live

**Comment by Stacyadam** [comment]
Okay I think the actual issue is that I am not updating it on the frontend after they are deleted. After I refresh the app the member card is deleted. I'll have this fixed tonight.

**Comment by Stacyadam** [comment]
Yeah at the time I worked on the Member Cards stuff the back end was still getting put together for it and I never revisited how it was handling the requests. I will put a flag or alert on the UI next time we run into this situation.
