### ISSUE TITLE
Request a Card not working yet?

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#19]
Looks like this form isn't actually submitting anything yet.  This should just be another form that passes through info to the info@smallshopsunited.com email (just like the Contact Us form).  

![image-1 5](https://user-images.githubusercontent.com/13523241/45658967-ab44e280-bab7-11e8-9d49-0e70bd517f1a.jpg)

**Comment by bryce13950** [comment]
@Stacyadam Was this working locally?

**Comment by Stacyadam** [comment]
@bryce13950 No this was never working.
![image](https://user-images.githubusercontent.com/33630849/45725890-97b27e00-bb82-11e8-8216-54790f9c393c.png)
![image](https://user-images.githubusercontent.com/33630849/45725896-a0a34f80-bb82-11e8-9674-73126b02f333.png)

**Comment by bryce13950** [comment]
Give it another shot

**Comment by Stacyadam** [comment]
Worked!
