### ISSUE TITLE
Hours of operation

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#20]
I just noticed an offer profile page that suggests the business is currently "closed", yet the hours of operation would suggest it's open.  I doubled checked it against google, and it should be "open" at the moment...

![image-1 6](https://user-images.githubusercontent.com/13523241/45659050-1db5c280-bab8-11e8-813a-21dbbb07b695.jpg)

![image-1 7](https://user-images.githubusercontent.com/13523241/45659054-20181c80-bab8-11e8-9145-95c030ef27d7.jpg)

**Comment by Stacyadam** [comment]
Okay I will look into it. The current hours seem to be working right now.

![image](https://user-images.githubusercontent.com/33630849/45726021-23c4a580-bb83-11e8-827f-348ab099ff07.png)

![image](https://user-images.githubusercontent.com/33630849/45726030-2a531d00-bb83-11e8-8907-eb7be5465ddf.png)
