### ISSUE TITLE
Date of Birth

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#21]
The date of birth field is mis-labeled at the moment (it's label reads "First Name").  Please change to "Date of Birth"

![image-1 8](https://user-images.githubusercontent.com/13523241/45659185-d3811100-bab8-11e8-8195-b33164f87111.jpg)

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45726103-79994d80-bb83-11e8-8258-14e3b26a3f45.png)
