### ISSUE TITLE
Changing password in settings

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#22]
We should be requiring the user to first enter their current password, then enter their new password.  This is an update that needs to be handled first on the back end.  It should be implemented for both the mobile app and the website.

We'll go ahead and release the mobile app without it for now, but we really should add it in one of the following updates.

**Comment by bryce13950** [comment]
This is already possible on the backend. You need to run a login with the current password, and then a update using the `/user/{id}` route

**Comment by tallmadge** [comment]
@bryce13950 I'm referring to the update to the password someone may want to do in their settings after they're already logged in.  They shouldn't be able to just enter a new password without first proving to us again that they're the owner of that account, which is why I'm suggesting we require the user to first confirm the current password before they get to enter a new password.  Is that what your above solution refers to?
![img_3069](https://user-images.githubusercontent.com/13523241/45692684-0101a500-bb21-11e8-9048-5a8cbc4bbf18.PNG)

**Comment by Stacyadam** [comment]
Was basing it off of what is currently being implemented on the website which just takes in a single new password.

![image](https://user-images.githubusercontent.com/33630849/45726150-b5ccae00-bb83-11e8-9025-affee891f9c9.png)

**Comment by bryce13950** [comment]
Yeah, if you want the user to confirm their password just run a login request again. It's probably a good idea on mobile, since the user could be logged in for a long period of time.

**Comment by tallmadge** [comment]
Seems to work.
