### ISSUE TITLE
Redeemed offer remaining in active list

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#23]
I just did a test redeeming an offer at a restaurant to see if it shows up properly in the 'Redeemed Offers' list.  I did properly show up in the Redeemed list, but it also remains in the active Gift Pack list, even after refreshing the list.

**Comment by Stacyadam** [comment]
Yeah that is by design based on the first conversation we had about promo codes not being able to be tracked. Unless I misunderstood I thought we decided to add them to the redeemed list instead of removing them from the active list.

**Comment by tallmadge** [comment]
That's only true of the promo code type offers.  Every other offer type needs to be removed from the active list once redeemed.  I would think that should be easy, because those will be the only offers that have been marked redeemed on the backend.

**Comment by Stacyadam** [comment]
Redeemed offers are now getting filtered out of any active offer lists. Pushing another build to TestFlight now.
