### ISSUE TITLE
Send email address with form data when user requests member card

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#24]
So, when the user requests a member card, I receive an email notification.  I'm getting everything the user submits when they complete the form (name, address), but I also need their email address.  Since they're already signed into the app when they request the card, I should think we can pass that info through without requiring the user to reenter it into this form.

**Comment by bryce13950** [comment]
I added it to the email. Nothing else needs to be done.
