### ISSUE TITLE
Use proper logo for Sign In/Sign Up page

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#25]
Update Sign In page to use proper logo file...

![image-1 9](https://user-images.githubusercontent.com/13523241/45793086-12000280-bc56-11e8-9412-a3029e3eff23.jpg)

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45923767-8df78600-beb4-11e8-92a6-402dd86ee79e.png)
