### ISSUE TITLE
New assets for Shop page

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#26]
Please replace the Gift Pack assets on the shop page with the following...

Please replace the current pricing stickers with the stickers you see below (orange for the 2019 Dine MKE, green for 2019 Explore MKE, blue for the 2019 Bundled Pack).

![ssu_webimage_package](https://user-images.githubusercontent.com/13523241/45905087-c2841880-bdb4-11e8-8078-224801479df5.png)

![copy of 2019 bundled pack sticker](https://user-images.githubusercontent.com/13523241/45905409-dbd99480-bdb5-11e8-9a35-d48123d4f1ce.png)

![copy of 2019 explore mke sticker](https://user-images.githubusercontent.com/13523241/45905412-df6d1b80-bdb5-11e8-9ede-fe6d14338080.png)

![copy of 2019 restaurant pack sticker](https://user-images.githubusercontent.com/13523241/45905425-e300a280-bdb5-11e8-9a98-0c57e235d8ca.png)

**Comment by Stacyadam** [comment]
Heres a screen cap of what the new sticker would look like.

![image](https://user-images.githubusercontent.com/33630849/45918454-eb57ec80-be4c-11e8-83d5-228fd393634a.png)

Here is my input.
1. Most of the text on the sticker is unreadable without making the generic Giftpack image 3x times bigger.
2. These assets would be better hosted somewhere and served from the backend along with their associated giftpack, something like `stickerURL`. I can put something together on the front end but it is going to be hacky and limited if we ever want to update these.

Let me know how you want to proceed.

**Comment by tallmadge** [comment]
Thanks for the input, Stacy.  That's just the kind of feedback I need to receive.  I'll create new sticker assets, and I'll assign them to @bryce13950 to implement with each package on the back end. 

I'll close this ticket, and then open a new one which I'll assign to Bryce.

**Comment by bryce13950** [comment]
@Stacyadam This is going to seem a bit counterintuitive, but could you include the images in issue #27 in the app, and then match them to gift pack ids? I know it sounds like a really bad idea, but adding an asset to a model on the backend, isn't incredibly simple, so it is something that I would probably not get to by launch.

**Comment by Stacyadam** [comment]
@bryce13950 Yeah that was what I came upon for implementing it on the front end. But that is so hacky :/. How is that supposed to scale? Every time we want to add or update a new sticker asset that means we have to process it on the front end, match the id with the giftPackId, manually assign it to the correlating gift pack, and then push another release. If you can't get to it by launch though I don't have an issue with implementing it this way temporarily.

**Comment by bryce13950** [comment]
Yep, just temporary.

**Comment by Stacyadam** [comment]
This is hooked up. The test account I have doesn't have access to the bundled giftpack though. What is the id for the 2019 Bundled Pack?

![2018-09-23_16-09-07](https://user-images.githubusercontent.com/33630849/45932997-0872e500-bf4b-11e8-8c36-ccab924865e2.png)

![2018-09-23_16-09-39](https://user-images.githubusercontent.com/33630849/45932999-16286a80-bf4b-11e8-8e8b-d792d18d7436.png)

**Comment by tallmadge** [comment]
I can't help you with the Bundled Pack ID.  That's a question that should be directed to @bryce13950 

So, how easy is it to swap out the assets once you've got them in there?

**Comment by Stacyadam** [comment]
Not that bad. It's just assigning the asset with the associated giftpack id. It's doable. Just kind of a silly thing to do on the front end.

**Comment by bryce13950** [comment]
The bundle id will be 1

**Comment by bryce13950** [comment]
BTW, the bundles are a separate endpoint. Not sure if you are loading them properly, but thought I would point that out

**Comment by Stacyadam** [comment]
That is good to know. All 3 are coming into the available gift pack products section now.

![image](https://user-images.githubusercontent.com/33630849/45958597-7b2ca080-bfdd-11e8-9e2c-36f979a4876a.png)

**Comment by tallmadge** [comment]
I just marked the two new Gift Packs plus the Bundled Pack 'active' (not hidden) in my admin.  These are the only Gift Packs marked as 'active', so they are the only Gift Packs that should be showing up in the website and the app Shop page.  However, in the app I'm now also seeing all of the Gift Packs that have not yet expired.  This means it's including the Gift Packs that I've got marked as 'inactive' (or hidden) in my admin.  Again, this can be confusing because of the fricken vernacular that was used.  

Bottom line, the Gift Packs that show up in the app Shop page must not have expired (seems you've got that done properly), but also must be marked 'active' in my admin.  As soon as I mark them as 'inactive', they should be hidden from this page.  If you're not sure of that end point, reach out to @bryce13950 

Lastly, I'm seeing the sticker assets for the Explore MKE and Bundled Packs, but for some reason the asset for the Dine MKE pack isn't showing up.  Also, why aren't the labels below the packages starting on the same line (see below)

![image-1 16](https://user-images.githubusercontent.com/13523241/45983047-a97f9f80-c020-11e8-90f2-5e6dfae5801a.jpg)

**Comment by Stacyadam** [comment]
Yeah it looks like the giftpack_id for that on the production api is 20167 and 20168...Its set to the production giftpack_id now.

![image](https://user-images.githubusercontent.com/33630849/45984949-65dd6380-c029-11e8-937d-bbc6c7c8df61.png)

**Comment by tallmadge** [comment]
The Shop page should only be pulling in Gift Packs marked visible.  I think you're pulling in any Gift Pack that hasn't expired at the moment.  I'm not sure what the end point is for visible vs hidden.  Maybe you already know that end point, or perhaps we need @bryce13950 to weigh in?  Below is a screen shot of what it looks like in my admin.  So, in this example, only the two packages marked at visible from the Gift Packs page, and the one Bundled Pack marked as visible from the Bundles page should be posting to the Shop page...

![image](https://user-images.githubusercontent.com/13523241/46158176-edea8580-c242-11e8-9430-437402c83091.png)

![image](https://user-images.githubusercontent.com/13523241/46158190-f478fd00-c242-11e8-84be-3a6a1d7f47a2.png)

**Comment by bryce13950** [comment]
The field we are using on this is `inactive` so if `inactive` is set to true then you should be skipping those gift packs.

**Comment by Stacyadam** [comment]
`inactive` isn't a bool it's an int. It looks like all of the giftpacks have an `inactive` of 1, including the ones that have not yet expired. So filtering by that would either show all of them or nothing.

![image](https://user-images.githubusercontent.com/33630849/46240177-22586180-c369-11e8-9eec-826a29f6ba9e.png)
![image](https://user-images.githubusercontent.com/33630849/46240183-34d29b00-c369-11e8-99b4-d1053ad8982d.png)

**Comment by bryce13950** [comment]
Yeah, I would just go ahead and do that. Once they are active then all of them will show properly, and that should be sometime next week.

**Comment by tallmadge** [comment]
Just tested this, and it looks to be working :)
