### ISSUE TITLE
Quick copy updates for FAQ

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#29]
Under Gift Packs, please make the following updates:

- [x] hyperlink www.smallshopsunited.com/activate in the answer under the question about how to activate my Gift Pack

- [x] Change the answer under 'How frequently can I redeem each Gift Pack offer?' to read as follows: "Generally speaking, each offer may be redeemed one time; however, there may be online offers that can be redeemed multiple times."

- [x] Change the answer under "How many Gift Packs can I add to my account?" to read: "Members are limited to one of each type of Gift Pack in their account at any one time."

**Comment by tallmadge** [comment]
Shoot!  I'm sorry, please make that hyperlink to www.smallshopsunited.com/giftpacks/activate

Sorry about that.  I'll close the ticket after that change.  The other items look good.

**Comment by Stacyadam** [comment]
Alright that has been updated.
