### ISSUE TITLE
Redeemed Offers should only be posted from active Gift Packs

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#3]
When the user searched by 'Redeemed Offers', we only want to post the redeemed offers from currently active Gift Packs.  So, once the Gift Pack expires, all the redeemed offers from that package should no longer post to this search.  (I'm currently seeing offers that were redeemed years ago)

**Comment by Stacyadam** [comment]
Okay this has been updated. Any gift_packs that have an inactive set to 1 are getting filtered out.
