### ISSUE TITLE
Why the Offer History filter?

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#30]
I just updated the app and now I'm starting on an "Offer History" filter when I go to my Gift Packs (see below).  I don't know what this means.  This page should default to "All Available Offers"

![image-1 15](https://user-images.githubusercontent.com/13523241/45934772-5c3ff700-bf68-11e8-837c-a7729d50a827.jpg)

**Comment by Stacyadam** [comment]
What if you buy a giftpack that doesn't have available offers until a certain date?

**Comment by tallmadge** [comment]
I thought that's what we discussed by phone the other day.  We're just going to add a valid beginning [date] through [date] to each offer, and then make sure they show up in the offer lists unless the offer is past it's expiration.

**Comment by Stacyadam** [comment]
No. We didn't discuss what the initial value for the dropdown modal would be in the case that the user purchased giftpacks that weren't available until a later date.

**Comment by tallmadge** [comment]
I explained it, but it appears you probably didn't understand what I was talking about.  I'll break down the scenarios for you below...

- If offer has not yet expired and Gift Pack has not yet expired, then post to available offers list or redeemed offer list

- If offer has expired, but Gift Pack has not yet expired, then remove from available offers, or continue to post in redeemed offer list if the offer was already redeemed 

- If offer has not yet expired, but Gift Pack has expired, remove from all lists

To eliminate any confusion for the user, we're going to replace the "information & restrictions" teaser with the offer valid dates to each offer (i.e. "Offer valid from [begin date] to [end date]").  We'll add it to the offer list, and again on the offer profile page.  For the profile page, we should add a "Valid" heading beneath "Conditions" and above "How to Redeem"

Here's what I'm thinking for the offers list page...

![image](https://user-images.githubusercontent.com/13523241/45955344-3e5cab80-bfd5-11e8-9529-ab720f40d118.png)

**Comment by Stacyadam** [comment]
The thing that I was questioning was the initial dropdown option of "All **Available** Offers" in the case that a user only has gift pack offers that aren't actually available yet. I am on the same page as you as far as getting more granular with each offer and conditionally rendering them based on if they are between the start and expiration date after it has been implemented on the back end.

This has been reverted to "All Available Offers"

![image](https://user-images.githubusercontent.com/33630849/45956252-aca26d80-bfd7-11e8-8ae2-506add7846b7.png)

![image](https://user-images.githubusercontent.com/33630849/45956261-b1672180-bfd7-11e8-8ec7-637dc73e549d.png)

**Comment by tallmadge** [comment]
Ah, I see... yeah, it could be a little confusing to categorize something that's not yet available under a heading called 'All Available Offers'.  Once Bryce adds the begin and end dates for the offers, would it be easy to only post offers that are within their active dates to the 'All Available Offers' list?  For example; if someone purchased the 2019 DINE MKE pack, none of those offers would show up in the 'All Available Offers' list, but the user could toggle down to the 2019 DINE MKE item in their menu to see the offers.

**Comment by Stacyadam** [comment]
Sounds good. I'll leave it as "All Available Offers" for now and we can play with whats actually going under that category after I implement the individual offer expiration parameters.

**Comment by tallmadge** [comment]
This looks good, but I'll leave the issue open until we determine how we handle the offers after implementing the offer expiration.
