### ISSUE TITLE
Offer index not matching the search

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#31]
In this latest version of the app, I was looking at the 'Redeemed Offers' list, then pulled down on the list to refresh just after adding the 2019 DINE MKE Pack to my member account from the back end.  I was then going to check the menu to see if the 2019 Dine MKE pack was now properly in my account, but what I found is that the index switched over to start showing all of the 2019 Dine MKE offers while I'm still looking at the 'Redeemed Offers' menu item (see screen shot below).  You'll notice those are not redeemed offers showing in the index.

![image-1 17](https://user-images.githubusercontent.com/13523241/46026317-b3e97a00-c0b0-11e8-9bea-2f79ac00a21d.jpg)

**Comment by Stacyadam** [comment]
Okay this is reverting back to the first index after a refresh brings in an additional giftpack.

**Comment by tallmadge** [comment]
I'll trust this is okay now.  I'll reopen later if I notice the issue again.
