### ISSUE TITLE
Pull down refresh doesn't appear to be pulling in new data

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#33]
It seems that I can't update data anymore when trying to refresh by pulling down on the Gift Pack index.

**Comment by Stacyadam** [comment]
Did you add an additional giftpack to the account? I updated it to fetch new data but only rerender if the new data is actually coming back with additional giftpacks.

**Comment by tallmadge** [comment]
No, but I updated data on different offers, and I moved to a different physical location.  Pulling down on the index was no longer changing the order of the offers based on proximity, nor did any of the new data show up in the offers (including new offers).  This all used to work in previous versions.

**Comment by Stacyadam** [comment]
Okay I reverted it to update regardless of if new giftpacks are retrieved. It will work the way it did before.

**Comment by tallmadge** [comment]
Looks like this is working again :)
