### ISSUE TITLE
Expiration dates (both Gift Packs and individual offers)

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#35]
1. @Stacyadam I'm noticing that there's still a time issue between the app and the actual time (seems like the app is something like 6 hours ahead of the actual time).

2. @bryce13950 The expiration dates should be through that date.  In other words, if I enter December 31st as the expiration date, the offer and/or Gift Pack should be active through that date.

**Comment by bryce13950** [comment]
The expiration date should work that way on my end. Is there any point where it doesn't?

**Comment by tallmadge** [comment]
I noticed last night that the Gift Pack expiration date was applying to the start of the date, rather than the end of that date.  I had created a test Gift Pack called Fake Pack, and originally set the expiration date of the package to 9/28/18.  I noticed after the latest app version update last night, that the offer from that package wasn't showing up in my app.  This was around 8pm last night, so I was thinking that perhaps the app time issue is coming up again, and the app thinks it's 6 hours later, which would put it at 2am on the 28th.  The Gift Pack should still be showing up with an expiration date set to the 28th.  That's what got me thinking that perhaps the expiration date is set to the beginning of that date (had the same problem with fundraising expirations when that platform first launched last year).  So, I changed the expiration date to 9/29/2018, and suddenly the Gift Pack was showing up in the app.  So, I'm assuming the two issues here; the app is not reading the proper time in the central time zone, and the expiration dates are being set to the start of that date, rather than the end of that date.

**Comment by tallmadge** [comment]
@Stacyadam This is one issue that still remains even after you pushed version number 25 through.  The good news is that the expiration date issue doesn't prevent us from launching the app.  

To be clear, if I set an expiration date to today's date, the Gift Pack/Offer should still be available throughout today.  Unfortunately, that's still not happening in the app.  A Gift Pack with an expiration set  to today is not showing up, so I assume you've got it set to expire at the start of the entered date, rather than the end of that date.

**Comment by Stacyadam** [comment]
Okay the date issues have been addressed. `starts_at` is now getting the time at the beginning of the day and `expires_at` is now getting the time for the end of the day.

**Comment by tallmadge** [comment]
I won't be able to test this until you push up an update.

**Comment by tallmadge** [comment]
This appears to be working now.
