### ISSUE TITLE
All Available Offers is not filtering properly by proximity

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#36]
Something is still not working properly with the index in All Available Offers.  The offers aren't organizing properly by proximity.

![image-1 20](https://user-images.githubusercontent.com/13523241/46183463-9413ab00-c296-11e8-85b7-cdb4ca6323c7.jpg)

**Comment by Stacyadam** [comment]
Looks like these weren't getting sorted properly after they were joined into one list. Added the sort and its working as expected.
