### ISSUE TITLE
Make sure Hours of Operation are matching the data properly

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#37]
Take a look at the screen shots below for Centro Cafe.  You can see that the data entered in my admin is not being reflected properly in the mobile app (it is showing up correctly on the ssu website).  The merchant is closed on Sundays and open on Mondays.  The app has it reversed.  This is consistent with other merchant hours that I'm seeing, as well.  I suspect this may be an issue with which day is considered the start of the week?  Also, is there an option to include "closed" on days that the merchant is closed (no data entered for that day)?

<img width="783" alt="centro cafe hours" src="https://user-images.githubusercontent.com/13523241/46212160-ea1a3a00-c2fa-11e8-9a6d-3d5a52430fa2.png">

![image-1 21](https://user-images.githubusercontent.com/13523241/46212124-d7076a00-c2fa-11e8-945d-dc50aa739f96.jpg)

**Comment by Stacyadam** [comment]
Yeah these weren't getting indexed starting with Sunday as 0. Fixed.
