### ISSUE TITLE
Create 200 unique promo codes for Original Cheesehead Factory

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#38]
Original Cheesehead Factory is running a multiple code offer, so I need you to create a batch of 200 unique codes that I can then send in Excel format to the vendor to upload into their purchasing software.  Obviously, you'll need to apply those codes to the offer on our end, as well.  

If it's easy enough, make the codes 8 digits all starting with ssu

**Comment by tallmadge** [comment]
You know several weeks ago I was asking you if we could generate promo codes, which I could both upload to the offer and then forward to the vendor to do the same on their end.  You insisted it would be easier for you to just generate the codes and link them to the offer right away, so you wanted me to give you the offer.  But, the offer hadn't been determined at that point, so I couldn't.

Now, I'm not sure what you're telling me.  Do you want to generate 200 codes to send to me, and then I'll upload them through my admin?  That's how we did it last year.

**Comment by bryce13950** [comment]
I think I was mistaken on which codes are which. I can create them, and upload them. Can you send me a link to the offer?

**Comment by tallmadge** [comment]
https://www.smallshopsunited.com/admin/merchants/10281/offers/626

Remember I'll need a csv file with those codes, too, in order to forward to the vendor.

**Comment by bryce13950** [comment]
Sending via slack
