### ISSUE TITLE
Add 'Redeemed On Date' to the redeemed offers

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#4]
Once an offer is redeemed, change the offer description to gray font and add the redeemed message in bold red font on the offer (in the Redeemed Offers table). example below...

**Offer Redeemed on 6/29/19** (but use red font)

![image-1 3](https://user-images.githubusercontent.com/13523241/45598348-2fa44200-b9a0-11e8-8bf5-897261ab89fc.jpg)

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45601206-fd5e0900-b9ce-11e8-96c4-dfb7af06a9f6.png)

**Comment by tallmadge** [comment]
The actual dates aren't coming through...

![redeemed on dates](https://user-images.githubusercontent.com/13523241/45658484-b3e7e980-bab4-11e8-8254-fef07b2c57a5.PNG)

**Comment by Stacyadam** [comment]
Okay apparently only the simulator has access to javascript Date methods... Fixed it.

![image](https://user-images.githubusercontent.com/33630849/45660302-ab47e100-babd-11e8-9d29-0cababb40341.png)

**Comment by tallmadge** [comment]
This appears to be working now :)

**Comment by tallmadge** [comment]
Actually, please order them by most recently redeemed on top

**Comment by bryce13950** [comment]
Yeah that's not going to work. Remember that offer_redemption model that we talked about? That is the model that has the redeemed information.

**Comment by tallmadge** [comment]
I think the timestamp may be off, because I just redeemed an offer around 8:30pm on 9/19/2018, however, it's showing up as redeemed on 9/20/2019 in the app

**Comment by bryce13950** [comment]
It's probably a timezone issue in the app. I believe the timestamps on the api are stored in Chicago time

**Comment by Stacyadam** [comment]
Yeah react-native doesn't support any localTime methods atm...which makes the already crappy javascript date handling even crappier. I was just putting the date together from what was in the response but I think I have a locale solution that will work. I'll push it to TestFlight later tonight.

**Comment by tallmadge** [comment]
I think you've got this fixed.  It's tricky to test, but I'm pretty sure it's working properly now.  I'll reopen if I notice any issues in future testing.
