### ISSUE TITLE
(Android) Image doesn't show up in Side Bar Menu

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#42]
![screenshot_20180930-180918](https://user-images.githubusercontent.com/13523241/46263979-6c158900-c4dc-11e8-9c5b-c203daf21876.png)

**Comment by Stacyadam** [comment]
This is working now. 
![image](https://user-images.githubusercontent.com/33630849/46322800-86b93200-c5b0-11e8-8d1e-23365c5ff8a3.png)
