### ISSUE TITLE
(Android) Updates to Personal Info and Contact Info not saving

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#44]
Can't save any changes to the Personal Info nor the Contact info in Android; however, updating the password is working.

![screenshot_20180930-182224](https://user-images.githubusercontent.com/13523241/46264096-06c29780-c4de-11e8-862d-a705d2ae0745.png)

**Comment by Stacyadam** [comment]
Was an issue with the data compiling before it sent the request. This is fixed.
