### ISSUE TITLE
(Android) Member Card request email is not triggering

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#45]
This action looks like it's submitting (I get the popup modal confirming the action), but I'm not receiving the request in my email.  I guess I don't know if this is an issue on the front end or back end.

**Comment by Stacyadam** [comment]
Getting a status OK on my end.

**Comment by tallmadge** [comment]
@bryce13950 Member Card requests are no longer triggering an email to me?  They seem to be going through fine in app (I'm getting confirmation messages), but I'm not getting an email alert.

**Comment by bryce13950** [comment]
There was a package that was not configured in production that needed to be added
