### ISSUE TITLE
Use this as the Loyalty icon

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#48]
![loyalty icon black](https://user-images.githubusercontent.com/13523241/47690231-3cc96900-dbbb-11e8-85c2-b517bc54edc5.png)

![loyalty icon orange](https://user-images.githubusercontent.com/13523241/47690235-4226b380-dbbb-11e8-8753-af234cbd7b6e.png)

**Comment by Stacyadam** [comment]
Going to need the first black check as a .svg in order to make that work.

**Comment by tallmadge** [comment]
I've just emailed you the svg file

**Comment by Stacyadam** [comment]
Looks like thats the image we are using for the location web links.
![image](https://user-images.githubusercontent.com/33630849/47954185-50772580-df55-11e8-92b1-9d38c6613b52.png)

**Comment by tallmadge** [comment]
Doh!  Sorry about that.  I just resent the proper file to your email.

**Comment by Stacyadam** [comment]
No biggy. Apps using this custom icon in place of the generic checkmark.
