### ISSUE TITLE
Loyalty Balance - tap to go to location profile

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#49]
Users need to be able to tap the location to get to the location profile from the Loyalty Balance page just like they can from the Locations index.

**Comment by Stacyadam** [comment]
Okay this is working now.

**Comment by tallmadge** [comment]
I can't seem to get anything to show up on the Balances page now...

![file nov 04 5 14 19 pm](https://user-images.githubusercontent.com/13523241/47971238-2c9b0900-e055-11e8-9bf3-7fa4e98793fb.jpeg)

**Comment by tallmadge** [comment]
Not sure what's going on... the balances come through fine when I sign in as my father, but I get nothing when signed into my own account.

**Comment by Stacyadam** [comment]
Yeah I am not experiencing that issue on the tshot@milwpc.com you gave me for testing or on my own personal account.  What's strange is I didn't touch the way that the balance data is getting brought into the app from the last build. If you give me the credentials for that account I can do some additional debugging.

**Comment by tallmadge** [comment]
use the following:
erictallmadge@gmail.com
ssunited

**Comment by Stacyadam** [comment]
Just needed some additional null checking. Works now.
![image](https://user-images.githubusercontent.com/33630849/48107654-09fc2200-e206-11e8-9ecf-707b321a2800.png)
