### ISSUE TITLE
Remove phone numbers from Locations index

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#50]
My fault... no need for the phone number on the index page.  Please remove and adjust spacing accordingly.

![file oct 29 8 53 02 pm](https://user-images.githubusercontent.com/13523241/47690617-b9a91280-dbbc-11e8-9a4a-1fb39368c91f.jpeg)

**Comment by Stacyadam** [comment]
Fixed.
