### ISSUE TITLE
Merchant accounts without a loyalty offer should not show up under loyalty

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#51]
I've noticed numerous accounts in the Locations index of the Loyalty section that don't have loyalty offers.  Those locations should not be showing up in this index.  Examples: Company Brewing, The Brass Alley, Three Lions Pub, etc.  

I assume you can just check for a loyalty offer, and if no or null the locations does not get posted to the loyalty index?

**Comment by Stacyadam** [comment]
Okay Locations is only bringing in locations that participate in the loyalty program.
