### ISSUE TITLE
Unexpected error when trying to view specific location profile pages

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#52]
I'm getting the below message when tapping on a few specific locations in the loyalty locations index page.  I get it when I tap Meraki and Hue Vietnamese Restaurants (both locations).  

![file oct 29 9 08 26 pm](https://user-images.githubusercontent.com/13523241/47691453-1c4fdd80-dbc0-11e8-9610-b871a118e9e9.jpeg)

**Comment by Stacyadam** [comment]
Fixed.
