### ISSUE TITLE
Make sure pulling down on index pages pulls in updated info

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#54]
I just had Bryce delete an old legacy location that was showing up in my rewards balance index, but when I pulled down on the list to refresh, it wasn't being removed.  It wasn't until I started the app over (cleared it from running) that the balances from that location were removed.

**Comment by Stacyadam** [comment]
It is fetching fresh data on the pull action. It might not be updating the List after though. I'll look into it.

![balancesfetch](https://user-images.githubusercontent.com/33630849/47737439-ef8edb00-dc3e-11e8-89db-ad7723734249.gif)

**Comment by Stacyadam** [comment]
This should be fixed. I don't have a solid way to test it though.

**Comment by tallmadge** [comment]
I'll close this issue, and reopen only if I notice it still being a problem
