### ISSUE TITLE
Add new copy section to location profile page design

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#55]
Please add orange header below 'Conditions' that reads "How to Earn/Redeem Rewards".  Then add the following copy... "Provide the merchant your member card or account phone number with every purchase to earn points or redeem your rewards."

We can just add this as part of the page design, because it's the same for all loyalty offers.

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/47969133-ba1c3000-e038-11e8-8339-972db5223f45.png)

**Comment by tallmadge** [comment]
Looks good.
