### ISSUE TITLE
Remove colons from offer detail headers on profile pages

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#56]
This goes for both Gift Pack offer profile pages and Loyalty Location profile pages... in order to be consistent I'd prefer we remove all colons from the orange headers in the offer details section at the bottom of the profile pages.

**Comment by Stacyadam** [comment]
Alright that has been cleaned up.

**Comment by tallmadge** [comment]
I'll assume this is done and close now.
