### ISSUE TITLE
Quick adjustments to Transactions index page

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#57]
- [ ] Remove "0" for the hour for morning time stamps.  (example: 08:06 AM should be 8:06 AM)

- [ ] Remove periods from both AM and PM

Also, how much can we play with the language when transcribing the transaction on this page?  Here are examples of how I'd prefer to present the copy, if possible...

**Current:** 
"Issued 2 Coffee or Tea Drink Card Credit"
**New:** 
"Issued 2 points on **Coffee or Tea Drink** Card

**Current:** 
"Redeemed $10 Off a Purchase of $30+"                         "Issued $2.08"
"From 2018 Restaurant Pack"
**New:**
"Redeemed $10 Off a Purchase of $30+"
"Issued $2.08 in loyalty credits"
(Add Gift Pack icon (see below) just below the time stamps)

**Current:**
"Redeemed 10 of credit"
"Issued 0 Coffee or Tea Drinks Card Credit"
**New:**
"Redeemed 1 **Coffee or Tea Drinks** Card

![gift pack icon orange](https://user-images.githubusercontent.com/13523241/47958519-a9b57800-df9a-11e8-9597-69843c1f4d70.png)

**Comment by Stacyadam** [comment]
Alright this has been updated.

**Comment by tallmadge** [comment]
I guess it looks a bit weird when the word "card" is not also in bold, so let's made that bold font, as well, and then we can close this.

**Comment by Stacyadam** [comment]
Okay thats been updated.
![image](https://user-images.githubusercontent.com/33630849/48106907-1468ec80-e203-11e8-9d93-9c13018c24e8.png)
