### ISSUE TITLE
How to handle multiple loyalty offers for a single location

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#58]
Make sure all loyalty offers fall under the Loyalty Offer heading on the location profile page.  In the example below, you'll see that one of the loyalty offers got moved down below the 'Conditions' heading.  It should be moved up to the Loyalty Offer section. (I believe this is the only example of a location that has both a credit type and a punch card type offer)

![file nov 04 7 03 41 pm](https://user-images.githubusercontent.com/13523241/47973276-49413c00-e069-11e8-9e93-806b9a3f9a07.jpeg)

**Comment by Stacyadam** [comment]
This is fixed.
![image](https://user-images.githubusercontent.com/33630849/48107589-d7522980-e205-11e8-8ba9-eb2bf2dde7d6.png)

**Comment by tallmadge** [comment]
I'll close this once I test it in app.
