### ISSUE TITLE
Home page audio

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#59]
- [ ] Make sure the title reads "A Love Letter to Milwaukee" (include quotation marks)

- [ ] Title the section "Featured Local Artist"

- [ ] Include small profile image (see below) with name: Kavon Cortez-Jones

![kavon cortez-jones 500 x 500](https://user-images.githubusercontent.com/13523241/47973664-3fb8d380-e06b-11e8-8c5b-83ed7ce23c7f.png)

**Comment by tallmadge** [comment]
I think this is turning out pretty great.  Kavon gave me four poems.  How easy (or difficult) would it be to let people swipe to get to more poems?  Kind of like the way you had it with the Gift Packs swiping to Loyalty, I wonder if people can tap an arrow or just swipe right to left to get to another poem.  

We don't have to do this by any means, but if it's a really quick thing to implement, let me know and I'll send you the three additional audio files.

**Comment by Stacyadam** [comment]
Now that the audio player component is in place it wouldn't be that hard to extend it. Design wise I think we would need a container for each poem.

**Comment by tallmadge** [comment]
I'm having a hard time with the left back arrow.  The right arrow is working nicely, but I'm having trouble tapping left to go back to previous poems.  Can you enlarge the sensitive area?

**Comment by Stacyadam** [comment]
Okay that has been fixed.
