### ISSUE TITLE
Refresh offers list

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#6]
The user should be able to refresh the offers list by dragging down the offers table.  For example; if I open the app in one part of town, then travel to another part of town, there's currently no way to refresh the list without closing the app from running in the background.  

The user should be able to pull down from the top of the list to refresh.

Also, should the list automatically refresh every time the app is opened?  What's standard practice?

**Comment by Stacyadam** [comment]
![2018-09-16_17-42-05](https://user-images.githubusercontent.com/33630849/45601766-d5bf6e80-b9d7-11e8-8694-eeac7f8a51c5.png)

**Comment by tallmadge** [comment]
I've sent the following image to use...

![800 x 800 ssu pin drop](https://user-images.githubusercontent.com/13523241/45659478-653d4e00-baba-11e8-82e9-50a94df5495c.png)

**Comment by Stacyadam** [comment]
Depends on the app. Right now the app is only fetching the data when the user opens the giftpacks screen. I think this is better in our case because it reduces the amount of initial requests needed before the app loads in case the user has a poor connection.

**Comment by tallmadge** [comment]
Okay, let's start this way.  If it becomes an issue as I start using it around town, I'll bring this up again :)

**Comment by Stacyadam** [comment]
👍
