### ISSUE TITLE
Ready to Redeem message

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#60]
"Ready to Redeem" should only show up when the user has enough credits to actually redeem.  This seems to be working properly for the 'punch card type' offers, but it's not following that rule when looking at store credits.  It seems that message is showing up no matter how many credits the user has.  For example, in the screen shot below you will see that the user has only $1.53 in credits at C-Viche, but you can see that the user needs $10 in order to redeem, so the message should only show if the user has $10+ credits for this location's offer.   It's working properly in the website, so I'm sure the proper end point or data should be available to do this.  

![file nov 06 9 47 31 pm](https://user-images.githubusercontent.com/13523241/48109755-52b7d900-e20e-11e8-9e5a-69a519efe13a.jpeg)

**Comment by Stacyadam** [comment]
Gotcha. That has been fixed.
![image](https://user-images.githubusercontent.com/33630849/48150624-cdbbd680-e284-11e8-84d9-291951e55d56.png)
