### ISSUE TITLE
Website icon not showing up in Android version

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#62]
![screenshot_20181108-220141](https://user-images.githubusercontent.com/13523241/48242739-3cdb1d00-e3a2-11e8-8547-663bc1c16562.png)

**Comment by Stacyadam** [comment]
Fixed.

**Comment by Stacyadam** [comment]
Each gift pack offers link is using the `location_website` property to populate that link.
![2018-11-11_18-11-58](https://user-images.githubusercontent.com/33630849/48320278-65029000-e5dd-11e8-8bee-aea034c3f82b.png)
![2018-11-11_18-13-10](https://user-images.githubusercontent.com/33630849/48320287-89f70300-e5dd-11e8-8201-06abdf34ff7f.gif)

I fixed the issue of it rendering the link if there was no `location_website` provided.

Pushing another version through TestFlight now.

**Comment by tallmadge** [comment]
Hmm... the one I tested when I added the last comment still seems to be a problem.  If you check out Skylight Music Theatre you'll notice that the website icon is linking to cart page of their website, but that's not the URL I entered when creating the Skylight Music Theatre location...

![image](https://user-images.githubusercontent.com/13523241/48320491-671a1e00-e5e0-11e8-8279-dac6355bab3d.png)

**Comment by tallmadge** [comment]
Yeah, I'm testing other Gift Pack offer profile pages, and they all seem to be linking to the Group Offer website data, rather than the location data.  Basically, whatever you're pulling from for the loyalty locations should be the same field you pull from for the Gift Pack offer profiles for these website icons.

**Comment by tallmadge** [comment]
The icon is linking properly now, but now the 'Go To Purchase' button is getting an error.

![file nov 11 9 01 45 pm](https://user-images.githubusercontent.com/13523241/48324133-3690af00-e5f5-11e8-9981-41f340dc8d70.jpeg)

**Comment by tallmadge** [comment]
There was no need to change the data you were using for the 'Go To Purchase' button, so I don't know if you messed around with this link?

**Comment by Stacyadam** [comment]
It wasn't messed with. There where multiple instances of `locationWebsite` that were getting fed into this component after it was updated to take in each locations website and the "Go To Purchase" link did not get updated properly with the new data coming in. Its fixed now.
