### ISSUE TITLE
Enlarge font for "Copy to Clipboard" on Gift Pack profile pages

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#63]
This message is difficult to read on both iOS and Android phones.  Let's bump up the font size and make sure it doesn't get cut off...

![screenshot_20181108-220141](https://user-images.githubusercontent.com/13523241/48242802-8166b880-e3a2-11e8-90af-2ff891980fb5.png)

**Comment by Stacyadam** [comment]
This has been updated.

**Comment by tallmadge** [comment]
Won't be able to test this is iPhone until you push up the next release, but it looks better in Android.  I'll assume it's been updated for both?  If so, you can close this issue.
