### ISSUE TITLE
Link in Gift Packs Help page not working in Android

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#64]
The hyperlink is not linking in Android on this page...

![screenshot_20181108-222645](https://user-images.githubusercontent.com/13523241/48290105-6bef9e00-e437-11e8-9f00-fe7f94333983.png)

**Comment by Stacyadam** [comment]
This has been fixed. Sending you an APK right now.

**Comment by tallmadge** [comment]
Looks like you made the entire answer a hyperlink, rather than just the URL in blue font.  Did you mean to do that?  Seems like it should just be the URL that links.

**Comment by Stacyadam** [comment]
Yeah that was intentional. The larger touchable surface area makes it easier to activate the link. I can change it to not alter the color when a user touches it if its an issue.

**Comment by tallmadge** [comment]
Okay.  It's fine as is, then.
