### ISSUE TITLE
New Gift Pack offer not showing up when I pull down refresh the index

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#65]
Just added a Gift Pack offer from Easy Tyger to the 2019 DINE MKE package, but I can't get it to show up when I pull down on the offers index to refresh the offers.

**Comment by tallmadge** [comment]
Actually, it just doesn't get pulled into the app at all.  I even closed the app from running in the background, reopened, and the new offer from Easy Tyger still doesn't show up in the 2019 DINE MKE list.

**Comment by tallmadge** [comment]
In fact, I'm noticing there are two Gift Pack offers that aren't showing up in the 2019 DINE MKE list, but I can't figure out why that would be.  The new one I just created (Easy Tyger), and Crafty Cow MKE.  I created that one a long time ago.  I don't see anything different about it from the offers that are showing up.

**Comment by Stacyadam** [comment]
Hmmm. Easy Tyger appears to be rendering in the list for me. This is what is coming back from the BE and how its rendering.
![image](https://user-images.githubusercontent.com/33630849/48508162-77fea580-e813-11e8-9517-19172d8a6ccc.png)
Crafty Cow appears to be rendering as well.

**Comment by Stacyadam** [comment]
Okay I just checked it out with your account. I see where the issue is. Working on a solution now.

**Comment by tallmadge** [comment]
Are you logged in as Eric Tallmadge?

--
Small Shops United

**Comment by Stacyadam** [comment]
Yeah it was filtering out the redeemed offers but wasn't doing it on a unique ID so they were getting removed from the wrong Giftpack. I'll push the fix to TestFlight in a bit.

**Comment by tallmadge** [comment]
Okay.  Looks good now.  We need to push this up to the stores right away.  Just emailed everyone today to download the app.  They’ll need to update now.  Can we force updates?

--
Small Shops United

**Comment by Stacyadam** [comment]
We can use code push to do that but it takes some work initially setting it up. I'll have another build in for review in a little bit.

**Comment by tallmadge** [comment]
I believe you've got this fixed.  Going to close, but I'll keep an eye on it the next time I create a new offer.
