### ISSUE TITLE
Change "Loyalty Offer" to "Gift Pack Offer"

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#7]
- [ ] Change the label from "Loyalty Offer" to "Gift Pack Offer"

- [ ] Change the icon from the check mark to the gift icon

![img_3068](https://user-images.githubusercontent.com/13523241/45598464-2a47f700-b9a2-11e8-944e-9a77ddd3f461.PNG)

**Comment by Stacyadam** [comment]
![image](https://user-images.githubusercontent.com/33630849/45601784-0dc6b180-b9d8-11e8-866e-4b0287bd43bc.png)
