### ISSUE TITLE
Back arrows are difficult to select

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#8]
I'm experiencing a lot of trouble using the back arrows.  They're not nearly sensitive enough for my iPhone 5S.  Takes me up to 5 or 6 times sometimes to get the page to go back.

**Comment by Stacyadam** [comment]
Okay. I increased the touchable surface area on those.

**Comment by tallmadge** [comment]
Did you increase the surface area for all of them?  I still have issues on the FAQ back arrow.  Otherwise, it's considerably better.

**Comment by Stacyadam** [comment]
Yeah that one got the increased are as well. This next push will have more room padding top on iPhone X's. That should resolve the overlap and the status bar interfering.

**Comment by tallmadge** [comment]
Yep.  Works smoothly now.
