### ISSUE TITLE
Update the pin on the maps

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#9]
Use the SSU square logo graphic on the pins, rather than Farm & Fleet :)

![img_3068](https://user-images.githubusercontent.com/13523241/45598504-91fe4200-b9a2-11e8-8d9c-142402c066db.PNG)

**Comment by Stacyadam** [comment]
Was going to use those until we had a pin asset. Here is what it looks like with the square logo.

![image](https://user-images.githubusercontent.com/33630849/45602010-d954f480-b9db-11e8-8b2e-5fbd46c0c7a0.png)

**Comment by tallmadge** [comment]
Yikes!  That doesn't look good.  What did you have in mind for the pin asset?

**Comment by Stacyadam** [comment]
I think if we just took it and added some radius spacing on the top and brought it down to a point it would work. I will email you the one we used for Blains.

**Comment by tallmadge** [comment]
Looks good.
